export type Language = 'en' | 'zh-HK';

export interface Translations {
  // Header
  title: string;
  subtitle: string;
  
  // Loading and error states
  loading: string;
  loadingMessage: string;
  error: string;
  
  // Buttons
  downloadOriginalCSV: string;
  downloadCSV: string;
  clearFilters: string;
  
  // Table headers
  reportsTableTitle: string;
  reportsCount: string;
  year: string;
  caseReference: string;
  titleEnglish: string;
  titleTraditionalChinese: string;
  titleSimplifiedChinese: string;
  titleTC: string;
  titleEN: string;
  titleCN: string;
  organizations: string;
  completedOn: string;
  reportType: string;
  viewFiles: string;
  
  // Filters
  searchPlaceholder: string;
  allYears: string;
  allTypes: string;
  allOrganizations: string;
  allLanguages: string;
  others: string;
  
  // Language filter options
  languageFilter: string;
  english: string;
  traditionalChinese: string;
  simplifiedChinese: string;
  
  // Messages
  noDataAvailable: string;
  noDataMessage: string;
  noMatchingReports: string;
  
  
  // File operations
  fileNotFound: string;
  errorAccessingFile: string;
  noFilePathAvailable: string;
  
  // Archive introduction
  archiveTitle: string;
  archiveDescription: string;
  archiveSource: string;
  fullTextSearchTitle: string;
  fullTextSearchDescription: string;
  archiveNote: string;
  lastUpdated: string;
}

export const translations: Record<Language, Translations> = {
  en: {
    // Header
    title: 'Hong Kong Ombudsman Reports',
    subtitle: 'Search and download Hong Kong Ombudsman reports from the generated reports table',
    
    // Loading and error states
    loading: 'Loading',
    loadingMessage: 'Loading reports table...',
    error: 'Error',
    
    // Buttons
    downloadOriginalCSV: 'Download Original CSV',
    downloadCSV: 'Download CSV',
    clearFilters: 'Clear Filters',
    
    // Table headers
    reportsTableTitle: 'Reports Table',
    reportsCount: 'reports',
    year: 'Year',
    caseReference: 'Case Reference',
    titleEnglish: 'Title (English)',
    titleTraditionalChinese: 'Title (Traditional Chinese)',
    titleSimplifiedChinese: 'Title (Simplified Chinese)',
    titleTC: 'Title (TC)',
    titleEN: 'Title (EN)',
    titleCN: 'Title (CN)',
    organizations: 'Organizations',
    completedOn: 'Completed On',
    reportType: 'Report Type',
    viewFiles: 'View Files',
    
    // Filters
    searchPlaceholder: 'Search reports...',
    allYears: 'All Years',
    allTypes: 'All Types',
    allOrganizations: 'All Organizations',
    allLanguages: 'All Languages',
    others: 'Others',
    
    // Language filter options
    languageFilter: 'Language',
    english: 'English',
    traditionalChinese: 'Traditional Chinese',
    simplifiedChinese: 'Simplified Chinese',
    
    // Messages
    noDataAvailable: 'No Data Available',
    noDataMessage: 'No reports data was found in the CSV file. Please ensure the reports_table.csv file has been generated by running the Python script generate_reports_table.py.',
    noMatchingReports: 'No reports match the current filters.',
    
    
    // File operations
    fileNotFound: 'File not found',
    errorAccessingFile: 'Error accessing file',
    noFilePathAvailable: 'No file path available for',
    
    // Archive introduction
    archiveTitle: 'About this Archive',
    archiveDescription: 'This webpage contains over 600 PDF reports and publications from the Hong Kong Office of The Ombudsman, published online between 1994 and May 2025. These documents are sourced from the Office\'s official website content, as preserved in the Internet Archive over the years.\n\nThe files were originally archived using the Wayback Machine by Archive-It (for the Government Records Service of Hong Kong), Archive Team, Alexa Internet, Common Crawl, and others.',
    archiveSource: 'The files were originally archived using the Wayback Machine by various organizations including Archive-It, Archive Team, Alexa Internet, and Common Crawl.',
    fullTextSearchTitle: 'Full-text Search',
    fullTextSearchDescription: 'The files have been organized and processed for OCR using artificial intelligence to facilitate searching. Users can also perform full-text searches within this archive\'s Pinpoint library. Google Boolean Search Operators can be used to refine searches for greater accuracy.',
    archiveNote: 'Please note that there may be omissions in the document library, and some file names may contain errors. We apologize for any inconvenience. Please visit this Github Repository to report errors or suggest additional documents.',
    lastUpdated: 'Last updated: 20 June, 2025'
  },
  
  'zh-HK': {
    // Header
    title: '香港申訴專員公署報告',
    subtitle: '搜尋及下載香港申訴專員公署報告',
    
    // Loading and error states
    loading: '載入中',
    loadingMessage: '正在載入報告表格...',
    error: '錯誤',
    
    // Buttons
    downloadOriginalCSV: '下載原始 CSV',
    downloadCSV: '下載 CSV',
    clearFilters: '清除篩選',
    
    // Table headers
    reportsTableTitle: '報告表格',
    reportsCount: '份報告',
    year: '年份',
    caseReference: '案件編號',
    titleEnglish: '標題（英文）',
    titleTraditionalChinese: '標題（繁體中文）',
    titleSimplifiedChinese: '標題（簡體中文）',
    titleTC: '標題 (繁體中文)',
    titleEN: '標題 (英文)',
    titleCN: '標題 (簡體中文)',
    organizations: '相關機構',
    completedOn: '完成日期',
    reportType: '報告類型',
    viewFiles: '檢視檔案',
    
    // Filters
    searchPlaceholder: '搜尋報告...',
    allYears: '所有年份',
    allTypes: '所有類型',
    allOrganizations: '所有機構',
    allLanguages: '所有語言',
    others: '其他',
    
    // Language filter options
    languageFilter: '語言',
    english: '英文',
    traditionalChinese: '繁體中文',
    simplifiedChinese: '簡體中文',
    
    // Messages
    noDataAvailable: '沒有可用資料',
    noDataMessage: '在 CSV 檔案中找不到報告資料。請確保已運行 Python 腳本 generate_reports_table.py 生成 reports_table.csv 檔案。',
    noMatchingReports: '沒有符合目前篩選條件的報告。',
    
    
    // File operations
    fileNotFound: '找不到檔案',
    errorAccessingFile: '存取檔案時發生錯誤',
    noFilePathAvailable: '沒有可用的檔案路徑',
    
    // Archive introduction
    archiveTitle: '文件庫簡介',
    archiveDescription: '此網頁收錄了香港申訴專員公署在1994年至2025年5月期間，於網上發表的600多份PDF報告及刊物。\n\n文件源自公署官方網站內容，備存於 Internet Archive 。檔案最初由Archive-It (for the Government Records Service of Hong Kong)、Archive Team、Alexa Internet、Common Crawl及其他方面，透過Wayback Machine進行備份。',
    archiveSource: '檔案最初由Archive-It、Archive Team、Alexa Internet、Common Crawl及其他方面，透過Wayback Machine進行備份。',
    fullTextSearchTitle: '內文搜尋',
    fullTextSearchDescription: '所有檔案均經人工智能整理並進行了光學字符識別（OCR）處理，以便於搜尋。使用者亦可前往此 Pinpoint 鏡像文件庫進行全文搜尋。使用者可使用 Google Boolean Search Operators 協助精準搜尋。',
    archiveNote: '請注意文件庫可能存在遺漏，部分檔案名稱也可能出現錯誤，敬請見諒。如欲回報錯誤或建議增補文件，請前往此 Github Repository 留言。',
    lastUpdated: '最後更新於： 2025年6月20日'
  }
};

// Language detection (client-side only)
export function detectBrowserLanguage(): Language {
  if (typeof navigator === 'undefined') {
    return 'zh-HK'; // Default to Traditional Chinese on server
  }
  
  const browserLang = navigator.language || navigator.languages[0];
  
  // Check for Chinese variants
  if (browserLang.startsWith('zh')) {
    // Check for Traditional Chinese variants
    if (browserLang.includes('HK') ||
        browserLang.includes('TW') ||
        browserLang.includes('MO') ||
        browserLang === 'zh-Hant') {
      return 'zh-HK';
    }
    // For other Chinese variants, still default to Traditional Chinese
    // since this is Hong Kong Ombudsman
    return 'zh-HK';
  }
  
  // For all other languages, use English
  return 'en';
}

// Parse Accept-Language header for server-side detection
export function parseAcceptLanguage(acceptLanguage: string): Language {
  if (!acceptLanguage) {
    return 'zh-HK'; // Default for Hong Kong context
  }

  // Parse Accept-Language header to find preferred languages
  const languages = acceptLanguage
    .split(',')
    .map(lang => {
      const [locale, q = '1'] = lang.trim().split(';q=');
      return {
        locale: locale.trim(),
        quality: parseFloat(q)
      };
    })
    .sort((a, b) => b.quality - a.quality);

  // Check for Chinese variants first
  for (const { locale } of languages) {
    if (locale.startsWith('zh')) {
      // Check for Traditional Chinese variants
      if (locale.includes('HK') ||
          locale.includes('TW') ||
          locale.includes('MO') ||
          locale === 'zh-Hant' ||
          locale === 'zh-TW' ||
          locale === 'zh-HK' ||
          locale === 'zh-MO') {
        return 'zh-HK';
      }
      // For Simplified Chinese, still default to Traditional Chinese
      // since this is Hong Kong Ombudsman
      return 'zh-HK';
    }
    
    // Check for English
    if (locale.startsWith('en')) {
      return 'en';
    }
  }
  
  // Default to Traditional Chinese for Hong Kong context
  return 'zh-HK';
}

// Get translations for a specific language
export function getTranslations(language: Language): Translations {
  return translations[language];
}

// Storage key for language preference
export const LANGUAGE_STORAGE_KEY = 'ombudsman-app-language';